---------------------------------------------------------------------
--정규화 실습

/*

요구사항

유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
아이들은 여러 번 체험학습에 등록할 수 있어요.

*/

-- CHAR
CREATE TABLE TBL_PARENT(
	ID NUMBER,
	PARENT_NAME VARCHAR2(255) NOT NULL,
	PARENT_AGE NUMBER,
	PARENT_ADDRESS VARCHAR2(255),
	PARENT_PHONE VARCHAR2(255) NOT NULL,
	PARENT_GENDER CHAR(5),
	CONSTRAINT PK_PARENT PRIMARY KEY(ID)
);

SELECT * FROM TBL_PARENT;

CREATE TABLE TBL_CHILD(
	ID NUMBER,
	CHILD_NAME VARCHAR2(255) NOT NULL,
	CHILD_AGE NUMBER,
	CHILD_GENDER CHAR(5),
	PARENT_ID NUMBER,
	CONSTRAINT PK_CHILD PRIMARY KEY(ID),
	CONSTRAINT FK_CHILD_PARENT FOREIGN KEY(PARENT_ID)
	REFERENCES TBL_PARENT(ID)
);

CREATE TABLE TBL_FIELD_TRIP_FILE(
	ID NUMBER,
	FILE_ORIGINAL_NAME VARCHAR2(255) NOT NULL,
	FILE_SYSTEM_NAME VARCHAR2(255),
	FILE_POSITION VARCHAR2(255),
	CONSTRAINT PK_FIELD_TRIP_FILE PRIMARY KEY(ID)
);

CREATE TABLE TBL_FILED_TRIP(
	ID NUMBER,
	FILED_TRIP_TITLE VARCHAR2(255),
	FILED_TRIP_CONTENT VARCHAR2(255),
	FIELD_TRIP_FILE_ID NUMBER,
	CONSTRAINT PK_FILED_TRIP PRIMARY KEY(ID),
	CONSTRAINT FK_FILED_TRIP_FILED_TRIP_FILE FOREIGN KEY(FIELD_TRIP_FILE_ID)
	REFERENCES TBL_FIELD_TRIP_FILE(ID)
);

CREATE TABLE TBL_APPLY(
	ID NUMBER,
	CHILD_ID NUMBER,
	FILED_TRIP_ID NUMBER,
	CONSTRAINT PK_APPLY PRIMARY KEY(ID),
	CONSTRAINT FK_APPLY_CHILD FOREIGN KEY(CHILD_ID)
	REFERENCES TBL_CHILD(ID),
	CONSTRAINT FK_APPLY_FILED_TRIP FOREIGN KEY(FILED_TRIP_ID)
	REFERENCES TBL_FILED_TRIP(ID)
);


------------------------------------------------------------------

/*
요구사항

안녕하세요, 광고 회사를 운영하려고 준비중인 사업가입니다.
광고주는 기업이고 기업 정보는 이름, 주소, 대표번호, 기업종류(스타트업, 중소기업, 중견기업, 대기업)입니다.
광고는 제목, 내용이 있고 기업은 여러 광고를 신청할 수 있습니다.
기업이 광고를 선택할 때에는 카테고리로 선택하며, 대카테고리, 중카테고리, 소카테고리가 있습니다.

*/

-- CONSTRAINT 제약조건명 CHECK(컬럼명 IN('값1', '값2', '값3');

CREATE TABLE TBL_COMPANY(
	ID NUMBER,
	COMPANY_NAME VARCHAR2(255) NOT NULL,
	COMPANY_ADDRESS VARCHAR2(255),
	COMPANY_TEL VARCHAR2(255),
	COMPANY_TYPE VARCHAR2(255) NOT NULL CONSTRAINT CHK_COMPANY_TYPE 
	CHECK(COMPANY_TYPE IN('스타트업', '중소기업', '중견기업', '대기업')),
	CONSTRAINT PK_COMPANY PRIMARY KEY(ID)
);

-- 카테고리 생성 대, 중, 소
CREATE TABLE TBL_CATEGORY_A(
	ID NUMBER,
	CATEGORY_A_NAME VARCHAR2(255) NOT NULL,
	CONSTRAINT PK_CATEGORY_A PRIMARY KEY(ID)
);

CREATE TABLE TBL_CATEGORY_B(
	ID NUMBER,
	CATEGORY_B_NAME VARCHAR2(255) NOT NULL,
	CATEGORY_A_ID NUMBER,
	CONSTRAINT PK_CATEGORY_B PRIMARY KEY(ID),
	CONSTRAINT FK_CATEGORY_B_CATEGORY_A FOREIGN KEY(CATEGORY_A_ID)
	REFERENCES TBL_CATEGORY_A(ID)
);

CREATE TABLE TBL_CATEGORY_C(
	ID NUMBER,
	CATEGORY_C_NAME VARCHAR2(255) NOT NULL,
	CATEGORY_B_ID NUMBER,
	CONSTRAINT PK_CATEGORY_C PRIMARY KEY(ID),
	CONSTRAINT FK_CATEGORY_C_CATEGORY_B FOREIGN KEY(CATEGORY_B_ID)
	REFERENCES TBL_CATEGORY_B(ID)
);

-- 광고
-- 광고는 제목, 내용, 카테고리
CREATE TABLE TBL_ADVER(
	ID NUMBER,
	ADVER_TITLE VARCHAR2(255),
	ADVER_CONTENT VARCHAR2(255),
	CATEGORY_C_ID NUMBER,
	CONSTRAINT PK_ADVER PRIMARY KEY(ID),
	CONSTRAINT FK_ADVER_CATEGORY_C FOREIGN KEY(CATEGORY_C_ID)
	REFERENCES TBL_CATEGORY_C(ID)
);


CREATE TABLE TBL_ADVER_APPLY(
	ID NUMBER,
	COMPANY_ID NUMBER NOT NULL,
	ADVER_ID NUMBER NOT NULL,
	CONSTRAINT PK_ADVER_APPLY PRIMARY KEY(ID),
	CONSTRAINT FK_ADVER_APPLY_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_ADVER_APPLY_ADVER FOREIGN KEY(ADVER_ID)
	REFERENCES TBL_ADVER(ID)
);

-------------------------------------------------------------------

/*
요구사항
음료수 판매 업체입니다. 음료수마다 당첨번호가 있습니다. 
음료수의 당첨번호는 1개이고 당첨자의 정보를 알아야 상품을 배송할 수 있습니다.
당첨 번호마다 당첨 상품이 있고, 당첨 상품이 배송 중인지 배송 완료인지 구분해야 합니다.
*/

CREATE TABLE TBL_MEMBER(
	ID NUMBER,
	MEMBER_ADDRESS VARCHAR2(255),
	CONSTRAINT PK_MEMBER PRIMARY KEY(ID)
);

CREATE TABLE TBL_SOFT_DRINK(
	ID NUMBER,
	SOFT_DRINK_NAME VARCHAR2(255),
	SOFT_DRINK_PRICE NUMBER DEFAULT 0,
	CONSTRAINT PK_SOFT_DRINK PRIMARY KEY(ID)
);


CREATE TABLE TBL_PRODUCT(
	ID NUMBER,
	PROIDUCT_NAME VARCHAR2(255) NOT  NULL,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(ID)
);

CREATE TABLE TBL_LOTTERY(
	ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT PK_LOTTERY PRIMARY KEY(ID),
	CONSTRAINT FK_LOTTERY_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

CREATE TABLE TBL_CIRCULATION(
	ID NUMBER,
	SOFT_DRINK_ID NUMBER,
	LOTTERY_ID NUMBER,
	CONSTRAINT PK_CIRCULATION PRIMARY KEY(ID),
	CONSTRAINT FK_CIRCULATION_SOFT_DRINK FOREIGN KEY(SOFT_DRINK_ID)
	REFERENCES TBL_SOFT_DRINK(ID),
	CONSTRAINT FK_CIRCULATION_LOTTRERY FOREIGN KEY(LOTTERY_ID)
	REFERENCES TBL_LOTTERY(ID)
);

CREATE TABLE TBL_DELEVERY(
	ID NUMBER,
	DELIVERY_STATUS VARCHAR2(255) DEFAULT 'READY',
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT PK_DELEVERY PRIMARY KEY(ID),
	CONSTRAINT FK_DELEVERY_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_DELEVERY_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);


---------------------------------------------------------------------

/*
요구사항
이커머스 창업 준비중입니다. 기업과 사용자 간 거래를 위해 기업의 정보와 사용자 정보가 필요합니다.
기업의 정보는 기업 이름, 주소, 대표번호가 있고
사용자 정보는 이름, 주소, 전화번호가 있습니다. 
결제 시 사용자 정보와 기업의 정보, 결제한 카드의 정보 모두 필요하며,
상품의 정보도 필요합니다. 상품의 정보는 이름, 가격, 재고입니다.
사용자는 등록한 카드의 정보를 저장할 수 있으며, 
카드의 정보는 카드번호, 카드사, 회원 정보가 필요합니다.
*/

CREATE TABLE TBL_COMPANY(
	ID NUMBER,
	COMPANY_NAME VARCHAR2(255),
	COMPANY_ADDRESS VARCHAR2(255),
	COMPANY_TEL VARCHAR2(255),
	CONSTRAINT PK_COMPANY PRIMARY KEY(ID)
);

CREATE TABLE TBL_MEMBER(
	ID NUMBER,
	MEMBER_NAME VARCHAR2(255),
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_PHONE VARCHAR2(255),
	CONSTRAINT PK_MEMBER PRIMARY KEY(ID)
);

CREATE TABLE TBL_PRODUCT(
	ID NUMBER,
	PRODUCT_NAME VARCHAR2(255),
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 0,
	COMPANY_ID NUMBER,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(ID),
	CONSTRAINT FK_PRODUCT_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID)
);

CREATE TABLE TBL_CARD(
	ID NUMBER,
	CARD_NUMBER VARCHAR2(255) NOT NULL,
	CARD_COMPANY VARCHAR2(255) NOT NULL,
	MEMBER_ID NUMBER,
	CONSTRAINT PK_CARD PRIMARY KEY(ID),
	CONSTRAINT FK_CARD_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

CREATE TABLE TBL_ORDER(
	ID NUMBER,
	ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	MEMBER_ID NUMBER,
	CONSTRAINT PK_ORDER PRIMARY KEY(ID),
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID)
);

CREATE TABLE TBL_ORDER_DETAIL(
	ID NUMBER,
	ORDER_DETAIL_PRODUCT_COUNT NUMBER DEFAULT 1,
	ORDER_ID NUMBER,
	PRODUCT_ID NUMBER,
	CONSTRAINT PK_ORDER_DETAIL PRIMARY KEY(ID),
	CONSTRAINT FK_ORDER_DETAIL_ORDER FOREIGN KEY(ORDER_ID)
	REFERENCES TBL_ORDER(ID),
	CONSTRAINT FK_ORDER_DETAIL_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

CREATE TABLE TBL_PAY(
	ID NUMBER,
	ORDER_ID NUMBER,
	CARD_ID NUMBER,
	CONSTRAINT PK_PAY PRIMARY KEY(ID),
	CONSTRAINT FK_PAY_ORDER FOREIGN KEY(ORDER_ID)
	REFERENCES TBL_ORDER(ID),
	CONSTRAINT FK_PAY_CARD FOREIGN KEY(CARD_ID)
	REFERENCES TBL_CARD(ID)
);






















