-- DML 
-- USER
-- 이름, 나이, 전화번호
CREATE TABLE TBL_USER(
	ID NUMBER,
	USER_NAME VARCHAR2(255),
	USER_AGE NUMBER,
	USER_PHONE VARCHAR2(255),
	CONSTRAINT PK_USER PRIMARY KEY(ID)
);

CREATE SEQUENCE USER_SEQ;

INSERT INTO TBL_USER
VALUES(USER_SEQ.NEXTVAL, '김세환', 20, '010-4709-9813');
INSERT INTO TBL_USER(ID, USER_NAME, USER_AGE, USER_PHONE)
VALUES(USER_SEQ.NEXTVAL, '홍길동', 20, '010-9999-7777');
INSERT INTO TBL_USER(ID, USER_NAME, USER_AGE, USER_PHONE)
VALUES(USER_SEQ.NEXTVAL, '이순신', 30, '010-4567-9090');
INSERT INTO TBL_USER(ID, USER_NAME, USER_AGE, USER_PHONE)
VALUES(USER_SEQ.NEXTVAL, '장보고', 35, '010-4456-3131');

DROP TABLE TBL_USER;

SELECT * FROM TBL_USER;
SELECT USER_NAME FROM TBL_USER;
SELECT USER_NAME, USER_PHONE FROM TBL_USER;

SELECT * FROM TBL_USER
WHERE USER_NAME='이순신';

SELECT * FROM TBL_USER
WHERE ID = 3;

SELECT * FROM TBL_USER 
WHERE USER_AGE >= 30 OR ID = '1';

-- 정렬 : ORDER BY (마지막)
-- 오름차순
SELECT * FROM TBL_USER 
ORDER BY USER_AGE ASC;

-- 내림차순
SELECT * FROM TBL_USER 
ORDER BY USER_AGE DESC;

-- 컬럼 순대로 (UTF-8)
SELECT * FROM TBL_USER 
ORDER BY USER_PHONE, USER_NAME;

-- 수정 : UPDATE ~ SET
UPDATE TBL_USER
SET USER_NAME='장보고'
WHERE ID=4;

SELECT * FROM TBL_USER;

-- 삭제
TRUNCATE TABLE TBL_USER;
DELETE FROM TBL_USER;













