CREATE TABLE TBL_MEMBER(
	ID NUMBER,
	MEMBER_ID VARCHAR2(255) NOT NULL,
	MEMBER_PASSWORD VARCHAR2(255) NOT NULL,
	MEMBER_NAME VARCHAR2(255) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_RECOMMENDER_ID VARCHAR2(255),
	CONSTRAINT PK_MEMBER PRIMARY KEY(ID)
);

CREATE SEQUENCE MEMBER_SEQ;

SELECT * FROM TBL_MEMBER;



INSERT INTO TBL_MEMBER(ID, MEMBER_ID, MEMBER_PASSWORD, MEMBER_NAME, MEMBER_ADDRESS) 
VALUES(MEMBER_SEQ.NEXTVAL, ?, ?, ?, ?)
