-- 요구사항
-- 회사에서 광고를 신청하려고 합니다.
-- 하나의 회사(TBL_COMPANY)는 여러개 광고(TBL_ADVER)는 
-- 여러개 신청(TBL_ADVER_FORM)할 수 있어야 합니다.
-- 회사 : 이름, 전화번호

CREATE TABLE TBL_COMPANY(
	ID NUMBER,
	COMPANY_NAME VARCHAR2(255),
	COMPANY_PHONE VARCHAR2(255) UNIQUE,
	CONSTRAINT PK_COMPANY PRIMARY KEY(ID)
);

-- 광고 : 광고이름, 컨텐츠
CREATE TABLE TBL_ADVER(
	ID NUMBER,
	ADVER_NAME VARCHAR2(255) NOT NULL,
	ADVER_CONTENT VARCHAR2(255) UNIQUE,
	CONSTRAINT PK_ADVER PRIMARY KEY(ID)
);

CREATE TABLE TBL_ADVER_FORM(
	ID NUMBER CONSTRAINT PK_ADVER_FORM PRIMARY KEY,
	COMPANY_ID NUMBER,
	ADVER_ID NUMBER,
	CONSTRAINT FK_ADVER_FORM_COMPANY FOREIGN KEY(COMPANY_ID)
	REFERENCES TBL_COMPANY(ID),
	CONSTRAINT FK_ADVER_FORM_ADVER FOREIGN KEY(ADVER_ID)
	REFERENCES TBL_ADVER(ID)
);

---------------------------------------------------------
--회원, 주문, 상품
CREATE TABLE TBL_MEMBER(
	ID NUMBER,
	MEMBER_ID VARCHAR2(255) UNIQUE NOT NULL,
	MEMBER_PW VARCHAR2(255) NOT NULL,
	MEMBER_ADDRESS VARCHAR2(255),
	MEMBER_EMAIL VARCHAR2(255),
	CONSTRAINT PK_MEMBER PRIMARY KEY(ID)
);

-- CITY
ALTER TABLE TBL_MEMBER RENAME COLUMN MEMBER_ADDRESS TO MEMBER_CITY;

CREATE TABLE TBL_PRODUCT(
	ID NUMBER,
	PRODUCT_NAME VARCHAR2(255),
	PRODUCT_PRICE NUMBER DEFAULT 0,
	PRODUCT_STOCK NUMBER DEFAULT 0,
	CONSTRAINT PK_PRODUCT PRIMARY KEY(ID)
);

CREATE TABLE TBL_ORDER(
	ID NUMBER,
	MEMBER_ID NUMBER,
	PRODUCT_ID NUMBER,
	ORDER_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_ORDER PRIMARY KEY(ID),
	CONSTRAINT FK_ORDER_MEMBER FOREIGN KEY(MEMBER_ID)
	REFERENCES TBL_MEMBER(ID),
	CONSTRAINT FK_ORDER_PRODUCT FOREIGN KEY(PRODUCT_ID)
	REFERENCES TBL_PRODUCT(ID)
);

-----------------------------------------------------------------------
-- 10분
-- 사용자(TBL_GOODS_USER)가 굿즈(TBL_GOODS)를 구매해서 선물하는
-- 선물하기(TBL_GIFTS) 기능이 필요해요.
-- 사용자 : 이름, 연락처, 주소
CREATE TABLE TBL_GOODS_USER(
	ID NUMBER,
	GOODS_USER_NAME VARCHAR2(255),
	GOODS_USER_PHONE VARCHAR2(255),
	GOODS_USER_ADDRESS VARCHAR2(255),
	CONSTRAINT PK_GOODS_USER PRIMARY KEY(ID)
);


-- 굿즈 : 상품명, 가격, 재고, 제작시간
CREATE TABLE TBL_GOODS(
	ID NUMBER,
	GOODS_NAME VARCHAR2(255) UNIQUE,
	GOODS_PRICE NUMBER DEFAULT 0,
	GOODS_STOCK NUMBER DEFAULT 0,
	GOODS_PRODUCE TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT PK_GOODS PRIMARY KEY(ID)
);

CREATE TABLE TBL_GIFTS(
	ID NUMBER,
	GOODS_USER_ID NUMBER,
	GOODS_ID NUMBER,
	CONSTRAINT PK_GIFTS PRIMARY KEY(ID),
	CONSTRAINT FK_GIFTS_GOODS_USER FOREIGN KEY(GOODS_USER_ID)
	REFERENCES TBL_GOODS_USER(ID),
	CONSTRAINT FK_GIFTS_GOODS FOREIGN KEY(GOODS_ID)
	REFERENCES TBL_GOODS(ID)
);

---------------------------------------------------------------------
--정규화 실습

/*

요구사항

유치원을 하려고 하는데, 아이들이 체험학습 프로그램을 신청해야 합니다.
아이들 정보는 이름, 나이, 성별이 필요하고 학부모는 이름, 나이, 주소, 전화번호, 성별이 필요해요
체험학습은 체험학습 제목, 체험학습 내용, 이벤트 이미지 여러 장이 필요합니다.
아이들은 여러 번 체험학습에 등록할 수 있어요.

*/













































